<?php

//    include/footer.inc
//    Footer section of every page
//
//    Part of the ht://Check package
//
//    Copyright (c) 1999-2000 Comune di Prato - Prato - Italy
//    Author: Gabriele Bartolini - Prato - Italy <angusgb@users.sourceforge.net>
//
//    For copyright details, see the file COPYING in your distribution
//    or the GNU General Public License version 2 or later 
//    <http://www.gnu.org/copyleft/gpl.html>
//
//    $Id: footer.inc,v 1.5 2000/10/16 16:06:57 angusgb Exp $

if ( defined( '__FOOTER_INC' ) ) return;
define( '__FOOTER_INC', 1 );

?>

<HR>

<%= $linkbar %>

</BODY>
</HTML>
